---
title: "Clustering_analysis"
author: "Gabriel Conte"
date: "2023-01-21"
output: html_document
---
##installing necessary packages 

```{r setup, include=FALSE}
install.packages("tidyverse") #collection of R packages designed for data science
install.packages("plotly") #graphic platform
install.packages("ggrepel") #text and label geoms for ggplot2 that help to avoid overlapping texts
install.packages("knitr") #table formatting
install.packages("kableExtra") #table formatting
install.packages("reshape2") #melt function
install.packages("cluster") #agnes function for creating hierarchical clusters
install.packages("factoextra") #fviz-dend function for building dendrograms
install.packages("ade4") #ade4 function for matrix of distances in binary var.
install.packages("misc3d") #3D graphics
install.packages("plot3D") #3D graphics
install.packages("openxlsx") #used to export the dataset to a excel file
```

##loading necessary packages

```{r}
library(tidyverse)
library(plotly)
library(ggrepel)
library(knitr)
library(kableExtra)
library(reshape2)
library(cluster)
library(factoextra)
library(ade4)
library(misc3d)
library(plot3D)
library(openxlsx)
```



